//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace konekcija
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public int LogID { get; set; }
        public string CardCode { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> ControllerID { get; set; }
        public int Direction { get; set; }
        public System.DateTime LocalTime { get; set; }
        public Nullable<int> CardholderID { get; set; }
    
        public virtual Cardholder Cardholder { get; set; }
    }
}
