//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace konekcija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int CardID { get; set; }
        public int CardholderID { get; set; }
        public string CardNo { get; set; }
        public string CardNoIntCode { get; set; }
        public byte CodeType { get; set; }
        public byte CardType { get; set; }
        public byte CardStatus { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public System.DateTime DeactivationDate { get; set; }
        public bool Deactivation { get; set; }
        public int AccessGroupID { get; set; }
        public string PinCode { get; set; }
        public byte Privilege { get; set; }
        public Nullable<int> AreaID { get; set; }
        public int FingerprintExist { get; set; }
        public int DataGroupID { get; set; }
        public bool DisableLockCard { get; set; }
    
        public virtual Cardholder Cardholder { get; set; }
    }
}
