//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace konekcija
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardholder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cardholder()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int CardholderID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool SendSMSMessage { get; set; }
        public string SMSMessage { get; set; }
        public string ID { get; set; }
        public bool Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string EmployeeID { get; set; }
        public string Home_Phone { get; set; }
        public string Home_Fax { get; set; }
        public string MobilePhone { get; set; }
        public string Home_ZipCode { get; set; }
        public string Home_Address { get; set; }
        public string Home_EMail { get; set; }
        public string Home_HomePage { get; set; }
        public string Home_Notes { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Department { get; set; }
        public string Office { get; set; }
        public string Office_Phone { get; set; }
        public string Office_Ext { get; set; }
        public string Office_Fax { get; set; }
        public string Office_CompanyName { get; set; }
        public string Office_ZipCode { get; set; }
        public string Office_Address { get; set; }
        public string Office_EMail { get; set; }
        public string Office_HomePage { get; set; }
        public string Office_Notes { get; set; }
        public string UserDefine01 { get; set; }
        public string UserDefine02 { get; set; }
        public string UserDefine03 { get; set; }
        public string UserDefine04 { get; set; }
        public string UserDefine05 { get; set; }
        public string UserDefine06 { get; set; }
        public string UserDefine07 { get; set; }
        public string UserDefine08 { get; set; }
        public string UserDefine09 { get; set; }
        public string UserDefine10 { get; set; }
        public string Photo { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string AD_GUID { get; set; }
        public byte[] Fingerprint01 { get; set; }
        public byte[] Fingerprint02 { get; set; }
        public byte[] Fingerprint03 { get; set; }
        public byte[] Fingerprint04 { get; set; }
        public byte[] Fingerprint05 { get; set; }
        public byte[] Fingerprint06 { get; set; }
        public byte[] Fingerprint07 { get; set; }
        public byte[] Fingerprint08 { get; set; }
        public byte[] Fingerprint09 { get; set; }
        public byte[] Fingerprint10 { get; set; }
        public int AntiDuressID { get; set; }
        public int CardholderType { get; set; }
        public string MiddleName { get; set; }
        public int DataGroupID { get; set; }
        public System.DateTime SeparationDate { get; set; }
        public string Division { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
    }
}
